# Generated by Django 2.2.14 on 2020-08-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.FileField(default='', upload_to='posts/photos/'),
        ),
    ]
